apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  RACK_ENV: 
  PORT: 
  MAX_THREADS: 
  MIN_THREADS: 
  PIDFILE: 
  WEB_CONCURRENCY: