services:
  redis:
    image: "redis:7.2.3-alpine"
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - "redis"
    command:
      [
        "bundle",
        "exec",
        "rerun",
        "--background",
        "--pattern",
        "**/*.{rb}",
        "--dir",
        "api,handlers,lib,spec",
        "--",
        "./bin/puma",
        "-C",
        "config/puma.rb",
      ]
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gems:/gems
    env_file:
      - .env
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - "redis"
    command:
      [
        "bundle",
        "exec",
        "rerun",
        "--background",
        "--pattern",
        "**/*.{rb}",
        "--dir",
        "api,handlers,lib,spec",
        "--",
        "./bin/sidekiq",
        "-r",
        "./config/sidekiq.rb",
        "-C",
        "config/sidekiq.yml"
      ]
    volumes:
      - .:/usr/src/app
      - gems:/gems
    env_file:
      - .env
volumes:
  redis:
  gems:
