namespace: development
domain: rack-api-development.codepop.services
image:
  repository: popac/rack-api-development
  tag: "c228a7578da7bb51ca952b016b612366fecdc042"
  restartPolicy: Always
  containerPort: 3000
replicaCount: 2
clusterIssuerName: codepop-services
ingressClassName: nginx
