namespace: staging
domain: rack-api-staging.codepop.services
image:
  repository: popac/rack-api-staging
  tag: ""
  restartPolicy: Always
  containerPort: 3000
replicaCount: 2
clusterIssuerName: codepop
ingressClassName: nginx
