apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  RACK_ENV: cHJvZHVjdGlvbg==
  PORT: MzAwMA==
  MAX_THREADS: NQ==
  MIN_THREADS: NQ==
  PIDFILE: dG1wL3BpZHMvc2VydmVyLnBpZA==
  WEB_CONCURRENCY: NA==
