apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        name: {{ .Chart.Name }}
    spec:
      containers:
        - args:
            - bundle
            - exec
            - puma
          env:
            - name: RACK_ENV
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: RACK_ENV
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: PORT
            - name: MAX_THREADS
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: MAX_THREADS
            - name: MIN_THREADS
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: MIN_THREADS
            - name: PIDFILE
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: PIDFILE
            - name: WEB_CONCURRENCY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: WEB_CONCURRENCY
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.image.containerPort }}
      restartPolicy: {{ .Values.image.restartPolicy }}