namespace: staging
domain: rack-api-staging.codepop.services
image:
  repository: popac/rack-api-staging
  tag: "ab439b8455f4ff9e382e38fe536f9a2da53dd1b5"
  restartPolicy: Always
  containerPort: 3000
replicaCount: 2
clusterIssuerName: codepop-services
ingressClassName: nginx
