apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rack-api-development
  namespace: argocd
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: "k8s/development"
    repoURL: git@github.com:mozgovac/rack-api.git
    targetRevision: development
  syncPolicy:
    automated: {}
