apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rack-api-production
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd
    notifications.argoproj.io/subscribe.on-deleted.slack: argocd
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argocd
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: "k8s/production"
    repoURL: git@github.com:alekpopovic/rack-api.git
    targetRevision: production
  syncPolicy:
    automated: {}
