apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rack-api-production
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: "k8s/production"
    repoURL: git@github.com:mozgovac/rack-api.git
    targetRevision: production
  syncPolicy:
    automated: {}
