apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rack-api-development
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd
    notifications.argoproj.io/subscribe.on-deleted.slack: argocd
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argocd
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd
    argocd-image-updater.argoproj.io/image-list: popac/rack-api-development
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: development
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: "helm/development"
    repoURL: git@github.com:alekpopovic/rack-api.git
    targetRevision: development
  syncPolicy:
    automated: {}
