namespace: production
domain: rack-api-production.codepop.services
image:
  repository: popac/rack-api-production
  tag: "3f340e9effef110a9f7ac21fa0ac27dd43bbb609"
  restartPolicy: Always
  containerPort: 3000
replicaCount: 3
clusterIssuerName: codepop-services
ingressClassName: nginx
