namespace: production
domain: rack-api-production.codepop.services
image:
  repository: popac/rack-api-production
  tag: ""
  restartPolicy: Always
  containerPort: 3000
replicaCount: 3
clusterIssuerName: codepop-services
ingressClassName: nginx
